thriftbp.WrapBaseplateError: Avoid double wrapping
Although we already added BaseplateErrorWrapper to client pool's default
middlewares, since all extra middlewares will be added after the default
middlewares, if user tries to add some error logging custom middleware,
they would need to add BaseplateErrorWrapper again so they can get the
wrapped error in their error logging middleware, and we end up having
double BaseplateErrorWrapper middleware in the chain.