batcherror: Better inspectibility with Is and As
Implement Is and As for BatchError so that any error inside the batch
can be inspected with errors.Is and errors.As, including wrapped ones.

Also remove Unwrap, as it's no longer useful.